-- 코드를 입력하세요
SELECT TITLE,BOARD_ID,REPLY_ID,B.WRITER_ID,B.CONTENTS,DATE_FORMAT(B.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD A JOIN USED_GOODS_REPLY B USING (BOARD_ID) 
WHERE YEAR(A.CREATED_DATE)=2022 AND MONTH(A.CREATED_DATE)=10
ORDER BY 6,1